---
title: "R Notebook"
output: html_notebook
---



```{r}
fm = read.csv("farmers_market_info.csv", na.strings="", stringsAsFactors=FALSE)
```

```{r}
#1. GEOGRAPHY 

#number of markets by state
fm$tally=1

library(dplyr)
state=summarise(group_by(fm,State),Total=sum(tally, na.rm=TRUE))

library(ggplot2)

ggplot(data=state, aes(x=reorder(State, -Total), y=Total)) +
  geom_bar(stat="identity", position=position_dodge(), fill="seagreen")+
  geom_text(aes(label=Total), angle = 0, hjust=-0.25, vjust=0.25, color="black",position = position_dodge(0.9), size=3.0)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+
  labs(x = "State", y = "Number of Farmers Markets")+
  ggtitle("Number of Farmers Markets in Each State") +coord_flip()





#number of markets by region
fm$region=1


fm$region=ifelse((fm$State=='California'| fm$State=="Oregon" | fm$State=='Washington' | fm$State=='New Mexico' | fm$State=='Arizona' | fm$State=='Colorado' | fm$State=='Utah' | fm$State=='Nevada' | fm$State=='Wyoming' | fm$State=='Idaho' | fm$State=='Montana') , "West", 
ifelse((fm$State=='New York'| fm$State=="Pennsylvania" | fm$State=='New Jersey' | fm$State=='Connecticut' | fm$State=='Massachusetts' | fm$State=='Vermont' | fm$State=='New Hampshire' | fm$State=='Rhode Island' | fm$State=='Maine'| fm$State=='Maryland' |fm$State=='District of Columbia'| fm$State=='Delaware'|fm$State=='Virginia') , "East", 
ifelse((fm$State=='Texas'| fm$State=="Oklahoma" | fm$State=='Arizona' | fm$State=='Louisiana' | fm$State=='Missouri' | fm$State=='Alabama' | fm$State=='Tennessee' | fm$State=='Kentucky' | fm$State=='Florida'|fm$State=='Georgia'| fm$State=='South Carolina' |fm$State=='North Carolina' |fm$State=='West Virginia'|fm$State=='Arkansas'|fm$State=='Mississippi') , "South",
ifelse((fm$State=='Ohio'| fm$State=="Indiana" | fm$State=='Illinois' | fm$State=='Michigan' | fm$State=='Wisconsin' | fm$State=='Kansas' | fm$State=='Nebraska' | fm$State=='Minnesota' | fm$State=='North Dakota' | fm$State=='South Dakota' | fm$State=='Indiana'|fm$State=='Iowa') , "MidWest",
ifelse((fm$State=='Alaska'| fm$State=="Hawaii" | fm$State=='Puerto Rico' | fm$State=='Virgin Islands') , "Pacific" ,NA
       )))))

Region=summarise(group_by(fm,region),Total=sum(tally, na.rm=TRUE))

ggplot(data=Region, aes(x=reorder(region,-Total), y=Total)) +
  geom_bar(stat="identity", position=position_dodge(), fill="orange")+
  geom_text(aes(label=Total), angle = 0, hjust=1.2, vjust=0.25, color="white",position = position_dodge(0.9), size=5.0)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+
  labs(x = "Region", y = "Number of Farmers Markets")+
  ggtitle("Number of Farmers Markets in Each US Region") +coord_flip()


```

```{r}
#Rate per population and area in State

#make population csv
#source: https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html
pop=read.csv("pop.csv", na.strings="", stringsAsFactors=FALSE)
colnames(pop)=c("State", "Population", "SqMiles")

#add new column to State
state$population=1
state$SqMiles=1

#fill in the values in state  using population csv
for (i in 1:57)
{
  temp=which(state$State==pop$State[i])
  state$population[temp]=pop$Population[i]
}

state[48,3]=107268

for (i in 1:57)
{
  temp=which(state$State==pop$State[i])
  state$SqMiles[temp]=pop$SqMiles[i]
}
state[48,4]=133.7

#calculations
state$perpop=1
state$perpop=round(((10000*state$Total)/state$population),digits=3)


state$permiles=1
state$permiles=round(((10*state$Total)/state$SqMiles),digits=3)


ggplot(data=state, aes(x=reorder(State,-perpop), y=perpop)) +
  geom_bar(stat="identity", position=position_dodge(), fill="orange")+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+
  labs(x = "State", y = "Number of Farmers Markets per 10,000 People")+
  ggtitle("Number of Farmers Markets in Each State Per 10,000 People") +coord_flip()+
  geom_text(aes(label=perpop), angle = 0, hjust=-0.25, vjust=0.25, color="black",position = position_dodge(0.9), size=3.0)


ggplot(data=state, aes(x=State, y=permiles)) +
  geom_bar(stat="identity", position=position_dodge(), fill="seagreen")+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+
  labs(x = "State", y = "Number of Farmers Markets per 10 sqMiles")+
  ggtitle("Number of Farmers Markets in Each State Per 10 sqMiles") +coord_flip()+
  geom_text(aes(label=permiles), angle = 0, hjust=-0.25, vjust=0.25, color="black",position = position_dodge(0.9), size=3.0)

```


```{r}
#2. TIME
fm2 <- subset(fm,select = c(FMID,MarketName,State,Season1Date))

library(stringr)
date=data.frame(str_split_fixed(fm2$Season1Date, " to ", 2))
year=data.frame(str_split_fixed(date$X1, "/", 3))

year=year[,-2]
colnames(year)=c("month", "year")
year$tally=1

#BY YEAR
dfyear=summarise(group_by(year,year),Total=sum(tally, na.rm=TRUE))
dfyear=dfyear[-c(1,2,13),]

ggplot(data=dfyear, aes(x=year, y=Total, group=1)) +geom_point(color="green")+geom_line(color="seagreen",size=1)+ylab("Number of Markets")+ggtitle("Number of Farmers Markets Each Year")




#BY MONTH
dfmonth=summarise(group_by(year,month),Total=sum(tally, na.rm=TRUE))
dfmonth=na.omit(dfmonth)

m1=dfmonth[2:10,]
  m1_1=data.frame(str_split_fixed(m1$month, "", 2))
  m1=cbind(m1_1$X2, m1$Total)
  colnames(m1)=c("month", "total")
  m1=data.frame(m1)

  
m2=dfmonth[11:20,]
  colnames(m2)=c("month", "total")


m3=dfmonth[21:60,]
  m3_1=data.frame(str_split_fixed(m3$month, " ", 2))
  m3_1$X1=as.character(m3_1$X1)
  m3_2=data.frame(str_split_fixed(m3_1$X1, "", 4))
library("tidyverse")
m3_3=m3_2 %>% mutate(x=str_c(X1,"",X2,"",X3))
  
  m3_4=data.frame(cbind(m3_3$x, m3$Total))
  m3=data.frame(m3_4)
  colnames(m3)=c("month", "total")
  m3=m3[order(m3$month),]

m3$x=1
 m3[1:3,3]=4 
 m3[4:5,3]=8
 m3[6,3]=12
 m3[10:15,3]=7
 m3[16:27,3]=6
 m3[28:36,3]=5
 m3[37:38,3]=11
 m3[39,3]=10
 m3[40,3]=9
 

m3=data.frame(cbind(m3$x, m3$total)) 
colnames(m3)=c("month", "total")
   

bymonth=data.frame(rbind(m1,m2,m3))
bymonth2=summarise(group_by(bymonth,month),Total=sum(total, na.rm=TRUE))
bymonth2$month=as.numeric(bymonth2$month)
bymonth3=bymonth2[order(bymonth2$month),]

ggplot(data=bymonth3, aes(x=month, y=Total, group=1)) +geom_point(color="red")+geom_line(color="salmon",size=1)+ylab("Number of Markets")+ggtitle("Number of Farmers Markets Starting By Month")+scale_x_continuous(breaks = seq(1, 12, by = 1))
#scale_x_discrete(labels=c("1" = "Jan", "2" = "Feb", "3" = "Mar", "4" = "Apr", "5" = "May", "6" = "Jun", "7"="Jul", "8"="Aug", "9"="Sep", "10"="Oct", "11"="Nov", "12"="Dec"))
  


#BY YEAR AND MONTH
dfym=summarise(group_by(year,year,month),Total=sum(tally, na.rm=TRUE))
dfym=dfym[-c(1:42),]

dfym[21,2]="01"
dfym[24,2]="06"
dfym[25,2]="07"
dfym[35,2]="01"
dfym[39,2]="05"
dfym[52,2]="05"
dfym[62,2]="01"
dfym[66,2]="02"
dfym[67,2]="03"
dfym[68,2]="05"
dfym[69,2]="06"
dfym[79,2]="01"
dfym[95,2]="04"

dfym$y=1
dfym[1,4]=10
dfym[2:4,4]=11
dfym[5:12,4]=12
dfym[13:25,4]=13
dfym[26:39,4]=14
dfym[40:52,4]=15
dfym[53:69,4]=16
dfym[70:82,4]=17
dfym[83:95,4]=18
dfym[96:107,4]=19

dfym$x=round(((as.numeric(as.character(dfym$month)))/12),digits=2)

dfym$time=dfym$y+dfym$x
dfym=dfym[-108,]


ggplot(dfym, aes(x=time, y=Total, group=1))+ylab("Number of Markets")+ggtitle("Number of Farmers Markets Starting in Each Month of Each Year")+xlab("Year")+theme(axis.text.x=element_text(angle = -270, hjust = 0))+ 
  geom_vline(xintercept=10, color="grey", size=0.75)+
geom_vline(xintercept=11, color="grey", size=0.75)+
geom_vline(xintercept=12, color="grey", size=0.75)+
  geom_vline(xintercept=13, color="grey", size=0.75)+
  geom_vline(xintercept=14, color="grey", size=0.75)+
  geom_vline(xintercept=15, color="grey", size=0.75)+
  geom_vline(xintercept=16, color="grey", size=0.75)+
  geom_vline(xintercept=17, color="grey", size=0.75)+
  geom_vline(xintercept=18, color="grey", size=0.75)+
  geom_vline(xintercept=19, color="grey", size=0.75)+
  geom_vline(xintercept=20, color="grey", size=0.75)+
  geom_line(color="orange",size=1)+geom_point(color="red")+
  scale_x_continuous(breaks= seq(10, 20, by = 1), labels=c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"))




```

```{r}
dz=dplyr::filter(fm,city== "Boston")

dz2=dz[,c(1,7)]
dz2=na.omit(dz2)

dz2$Season1Time=c(11,8,11,11,11,11,10)
dz2$end=c(15,16,15,18,18,18,16)

d1=data.frame(cbind(dz2$FMID,dz2$Season1Time))
d1$value="start"
colnames(d1)=c("Market_ID", "Time", "Value")

d2=data.frame(cbind(dz2$FMID,dz2$end))
d2$value="end"
colnames(d2)=c("Market_ID", "Time", "Value")

d3=rbind(d1,d2)

d3$Market_ID=as.character(d3$Market_ID)

ggplot(d3, aes(x=Time, y=Market_ID, group=Market_ID)) +
  geom_line(aes(color=Market_ID))+
  geom_point(color="red")+ylab("Market ID")+xlab("Time of Day")+ggtitle("Schedule of Massachusetts Markets")+
  scale_x_continuous(breaks= seq(8, 19, by = 1),labels=c("8 am", "9 am", "10 am", "11 am", "12 pm", "1 pm", "2 pm", "3 pm", "4 pm", "5 pm", "6 pm", "7 pm"))
  

```


```{r}
#PRODUCT
#number of markets selling each product

fm3=fm[,c(4, 6, 23:53)]

find_Y<-function(col_name){
        nb<-as.numeric(unname(table(col_name)["Y"]))
        return(nb)
}

fm3_1<-fm3%>%
        select(Bakedgoods:Tofu)%>%
        summarise_all(funs(find_Y))

farmers3<-data.frame(matrix(0,nrow=ncol(fm3_1), ncol=2))
names(farmers3)<-c("Product_Type","Amount")
farmers3$Product_Type<-names(fm3_1)
farmers3$Amount<-unlist(fm3_1)


ggplot(farmers3, aes(x=as.factor(Product_Type), y=Amount)) +
geom_bar(stat="identity", fill=alpha("seagreen"))+
  coord_polar(start = 0)+
  ylim(-500,5000) +
  xlab("Product Type") + ylab("Number of Farmer Markets")+
  ggtitle("Number of Farmer Markets Selling Each Product")
  

#number of markets selling each product group

#write.csv(farmers3, file = "prod.csv")

groups = read.csv("prod.csv", na.strings="", stringsAsFactors=FALSE)
groups=summarise(group_by(groups,Group),Total=sum(Amount, na.rm=TRUE))

ggplot(data=groups, aes(x=reorder(Group, -Total), y=Total)) +
geom_bar(stat="identity", fill=alpha("orange"))+
  ggtitle("Number of Markets Selling Each Product Type")+
  xlab("Product Group")+ylab("Number of Markets")+
  geom_text(aes(label=Total), angle = 0, hjust=0.5, vjust=-0.75, color="black",position = position_dodge(0.9), size=5.0)



```

```{r}
#what percent of markets sell each product in each state
#fm3$tally=1

library(tidyr)
library(reshape2)

#baked
b1=summarise(group_by(fm3,region,Bakedgoods),baked=sum(tally, na.rm=TRUE))
b1=na.omit(b1)
b2=dcast(b1, region ~ Bakedgoods, mean)
b2$Baked_portion=1
b2$Baked_portion=round(((b2$Y/(b2$Y+b2$N))*100),digits=0)
b2$Baked_portion <- replace(b2$Baked_portion, is.nan(b2$Baked_portion), 0)

#cheese
c1=summarise(group_by(fm3,region,Cheese),cheese=sum(tally, na.rm=TRUE))
c1=na.omit(c1)
c2=dcast(c1, region ~ Cheese, mean)
c2$Cheese_portion=1
c2$Cheese_portion=round(((c2$Y/(c2$Y+c2$N))*100),digits=0)
c2$Cheese_portion <- replace(c2$Cheese_portion, is.nan(c2$Cheese_portion), 0)

#seafood
s1=summarise(group_by(fm3,region,Seafood),Seaf=sum(tally, na.rm=TRUE))
s1=na.omit(s1)
s2=dcast(s1, region ~ Seafood, mean)
s2$seafood_portion=1
s2$seafood_portion=round(((s2$Y/(s2$Y+s2$N))*100),digits=0)
s2$seafood_portion <- replace(s2$seafood_portion, is.nan(s2$seafood_portion), 0)

#meat
m1=summarise(group_by(fm3,region,Meat),m=sum(tally, na.rm=TRUE))
m1=na.omit(m1)
m2=dcast(m1, region ~ Meat, mean)
m2$meat_portion=1
m2$meat_portion=round(((m2$Y/(m2$Y+m2$N))*100),digits=0)
m2$meat_portion <- replace(m2$meat_portion, is.nan(m2$meat_portion), 0)

#vegetables
v1=summarise(group_by(fm3,region,Vegetables),veg=sum(tally, na.rm=TRUE))
v1=na.omit(v1)
v2=dcast(v1, region ~ Vegetables, mean)
v2$vegetable_portion=1
v2$vegetable_portion=round(((v2$Y/(v2$Y+v2$N))*100),digits=0)
v2$vegetable_portion <- replace(v2$vegetable_portion, is.nan(v2$vegetable_portion), 0)

#jams
j1=summarise(group_by(fm3,region,Jams),jam=sum(tally, na.rm=TRUE))
j1=na.omit(j1)
j2=dcast(j1, region ~ Jams, mean)
j2$jam_portion=1
j2$jam_portion=round(((j2$Y/(j2$Y+j2$N))*100),digits=0)
j2$jam_portion <- replace(j2$jam_portion, is.nan(j2$jam_portion), 0)

#wine
w1=summarise(group_by(fm3,region,Wine),win=sum(tally, na.rm=TRUE))
w1=na.omit(w1)
w2=dcast(w1, region ~ Wine, mean)
w2$wine_portion=1
w2$wine_portion=round(((w2$Y/(w2$Y+w2$N))*100),digits=0)
w2$wine_portion <- replace(w2$wine_portion, is.nan(w2$wine_portion), 0)

#petfood
p1=summarise(group_by(fm3,region,PetFood),pet=sum(tally, na.rm=TRUE))
p1=na.omit(p1)
p2=dcast(p1, region ~ PetFood, mean)
p2$pet_portion=1
p2$pet_portion=round(((p2$Y/(p2$Y+p2$N))*100),digits=0)
p2$pet_portion <- replace(p2$pet_portion, is.nan(p2$pet_portion), 0)

#fruits
f1=summarise(group_by(fm3,region,Fruits),fruit=sum(tally, na.rm=TRUE))
f1=na.omit(f1)
f2=dcast(f1, region ~ Fruits, mean)
f2$fruit_portion=1
f2$fruit_portion=round(((f2$Y/(f2$Y+f2$N))*100),digits=0)
f2$fruit_portion <- replace(f2$fruit_portion, is.nan(f2$fruit_portion), 0)

#crafts
cr1=summarise(group_by(fm3,region,Crafts),crf=sum(tally, na.rm=TRUE))
cr1=na.omit(cr1)
cr2=dcast(cr1, region ~ Crafts, mean)
cr2$craft_portion=1
cr2$craft_portion=round(((cr2$Y/(cr2$Y+cr2$N))*100),digits=0)
cr2$craft_portion <- replace(cr2$craft_portion, is.nan(cr2$craft_portion), 0)


Portions=data.frame(cbind(b2$region, b2$Baked_portion, c2$Cheese_portion, s2$seafood_portion, m2$meat_portion, v2$vegetable_portion, j2$jam_portion, w2$wine_portion, p2$pet_portion, f2$fruit_portion, cr2$craft_portion))

colnames(Portions)=c("region", "Bakery", "Cheese", "Seafood", "Meat", "Vegetable", "Jam", "Wine", "PetFood", "Fruit",  "Crafts")

portions2<- melt(Portions[,c("region", "Bakery", "Cheese", "Seafood", "Meat", "Vegetable", "Jam", "Wine", "PetFood", "Fruit",  "Crafts")],id.vars = 1)

portions2$value=as.numeric(as.character(portions2$value))

ggplot(portions2,aes(x = region,y = value)) + 
    geom_bar(aes(fill = variable),stat = "identity",position = "dodge")+scale_fill_brewer(palette="Paired")+
  ggtitle("Percent of Markets In Each Region That Sell Each Product")+theme_light()+ylab("Percent of Total Markets in Each Region")



ggplot(portions2, aes(x=region,y=variable ,fill=value)) +geom_tile()+ylab("Product")+ggtitle("Popularity of Products by Region")+labs(fill = "Percent of Markets In The Region")+scale_fill_distiller(palette ="Rd", direction = 1)


```

```{r}
#PAYMENTS

#percent of markets in each region tha accept each payment type
fm4=fm[,c(4,17:21,52:53)]

#credit
pc1=summarise(group_by(fm4,region,Credit),cr=sum(tally, na.rm=TRUE))
pc1=na.omit(pc1)
pc2=dcast(pc1, region ~ Credit, mean)
pc2$credit_portion=1
pc2$credit_portion=round(((pc2$Y/(pc2$Y+pc2$N))*100),digits=0)
pc2$credit_portion <- replace(pc2$credit_portion, is.nan(pc2$credit_portion), 0)

#WIC
pw1=summarise(group_by(fm4,region,WIC),wic=sum(tally, na.rm=TRUE))
pw1=na.omit(pw1)
pw2=dcast(pw1, region ~ WIC, mean)
pw2$wic_portion=1
pw2$wic_portion=round(((pw2$Y/(pw2$Y+pw2$N))*100),digits=0)
pw2$wic_portion <- replace(pw2$wic_portion, is.nan(pw2$wic_portion), 0)

#WICcash
pwc1=summarise(group_by(fm4,region,WICcash),wiccash=sum(tally, na.rm=TRUE))
pwc1=na.omit(pwc1)
pwc2=dcast(pwc1, region ~ WICcash, mean)
pwc2$wiccash_portion=1
pwc2$wiccash_portion=round(((pwc2$Y/(pwc2$Y+pwc2$N))*100),digits=0)
pwc2$wiccash_portion <- replace(pwc2$wiccash_portion, is.nan(pwc2$wiccash_portion), 0)

#SFMNP
ps1=summarise(group_by(fm4,region,SFMNP),sfn=sum(tally, na.rm=TRUE))
ps1=na.omit(ps1)
ps2=dcast(ps1, region ~ SFMNP, mean)
ps2$sf_portion=1
ps2$sf_portion=round(((ps2$Y/(ps2$Y+ps2$N))*100),digits=0)
ps2$sf_portion <- replace(ps2$sf_portion, is.nan(ps2$sf_portion), 0)

#SNAP
pn1=summarise(group_by(fm4,region,SNAP),snap=sum(tally, na.rm=TRUE))
pn1=na.omit(pn1)
pn2=dcast(pn1, region ~ SNAP, mean)
pn2$snap_portion=1
pn2$snap_portion=round(((pn2$Y/(pn2$Y+pn2$N))*100),digits=0)
pn2$snap_portion <- replace(pn2$snap_portion, is.nan(pn2$snap_portion), 0)



payportions=data.frame(cbind(pc2$region, pc2$credit_portion, pw2$wic_portion, pwc2$wiccash_portion, ps2$sf_portion, pn2$snap_portion))

colnames(payportions)=c("region", "Credit", "WIC", "WICcash", "SFNP", "SNAP")

payportions2<- melt(payportions[,c("region", "Credit", "WIC", "WICcash", "SFNP", "SNAP")],id.vars = 1)

payportions2$value=as.numeric(as.character(payportions2$value))

ggplot(payportions2,aes(x = region,y = value)) + 
    geom_bar(aes(fill = variable),stat = "identity",position = "dodge")+scale_fill_brewer(palette="Paired")+
  ggtitle("Percent of Markets In Each Region That Accept Each Pay Method")+theme_light()+ylab("Percent of Total Markets in Each Region")


ggplot(payportions2, aes(x=region,y=variable ,fill=value)) +geom_tile()+ylab("Payment Type")+ggtitle("Percent of Markets in Each Region That Accept Each Pay Method")+labs(fill = "Percent of Markets")+scale_fill_distiller(palette ="Rd", direction = 1)

```

```{r}
#INTERSECTION
fm5=data.frame(cbind(fm4,fm$city))
sec=dplyr::filter(fm5,fm.city== "Boston")

pie=setNames(data.frame(matrix(ncol = 3, nrow =5)), c("Payment_Types","Count", "Portion"))

pie$Payment_Types=c("None", "Credit", "WIC & SNAP", "Credit, WIC, SFNP, SNAP", "Credit, WICcash, SFMNP, SNAP")
pie$Count=c(3,2,1,3,1)
pie$Portion=(pie$Count/10)*100

#Piechart using NU_Average per day
ggplot(pie, aes(x="", y=Portion, fill=Payment_Types))+
  geom_bar(width = 1, stat = "identity")+coord_polar("y", start=0)+
  geom_text(aes(y = c(0.25, 0.9, 0.06, 0.68, 0.45),label = Portion), size=3)+
  scale_fill_brewer(palette = "OrRd")+
  ggtitle("Massachusetts: Fraction of markets that accept different payment types")



pie2=setNames(data.frame(matrix(ncol = 3, nrow =4)), c("Number_of_Payment_Types","Count", "Portion"))

pie2$Payment_Types=c("None", "Accept 1", "Accept 2", "Accept 4")

pie2$Count=c(3,2,1,4)

pie2$Portion=pie2$Count/10

#Piechart using NU_Average per day
ggplot(pie2, aes(x="", y=Portion, fill=Payment_Types))+
  geom_bar(width = 1, stat = "identity")+coord_polar("y", start=0)+
  geom_text(aes(y = c(0.2, 0.9, 0.75, 0.5),label = Portion), size=3)+
  scale_fill_brewer(palette = "OrRd")+
  ggtitle("Fraction of markets that accept different number of payment types")

```


```{r}
#COMBINE

#popularity of product over the months
comb=data.frame(cbind(year,fm3))
comb=comb[,-5]

cb1=summarise(group_by(comb,month,Bakedgoods),baked=sum(tally, na.rm=TRUE))
cb1=na.omit(cb1)
cb2=dcast(cb1, month ~ Bakedgoods, mean)
cb2$Baked_portion=1
cb2$Baked_portion=round(((cb2$Y/(cb2$Y+cb2$N))*100),digits=0)
cb2$Baked_portion <- replace(cb2$Baked_portion, is.nan(cb2$Baked_portion), 0)


cc1=summarise(group_by(comb,month,Cheese),cheese=sum(tally, na.rm=TRUE))
cc1=na.omit(cc1)
cc2=dcast(cc1, month ~ Cheese, mean)
cc2$Cheese_portion=1
cc2$Cheese_portion=round(((cc2$Y/(cc2$Y+cc2$N))*100),digits=0)
cc2$Cheese_portion <- replace(cc2$Cheese_portion, is.nan(cc2$Cheese_portion), 0)


cj1=summarise(group_by(comb,month,Jams),jam=sum(tally, na.rm=TRUE))
cj1=na.omit(cj1)
cj2=dcast(cj1, month~ Jams, mean)
cj2$jam_portion=1
cj2$jam_portion=round(((cj2$Y/(cj2$Y+cj2$N))*100),digits=0)
cj2$jam_portion <- replace(cj2$jam_portion, is.nan(cj2$jam_portion), 0)


cm1=summarise(group_by(comb,month,Maple),maple=sum(tally, na.rm=TRUE))
cm1=na.omit(cm1)
cm2=dcast(cm1, month ~ Maple, mean)
cm2$maple_portion=1
cm2$maple_portion=round(((cm2$Y/(cm2$Y+cm2$N))*100),digits=0)
cm2$maple_portion <- replace(cm2$maple_portion, is.nan(cm2$maple_portion), 0)


#write.csv(cb2, file = "cb.csv")
cb=read.csv("cb.csv", na.strings="", stringsAsFactors=FALSE)


combportions=data.frame(cbind(cb$month, cb2$Baked_portion, cc2$Cheese_portion,cj2$jam_portion, cm2$maple_portion))


colnames(combportions)=c("Month", "Bakery", "Cheese", "Jam", "Maple")
combportions=combportions[-c(1,60),]

combportions$Maple=as.numeric(as.character(combportions$Maple))
combportions$Jam=as.numeric(as.character(combportions$Jam))
combportions$Cheese=as.numeric(as.character(combportions$Cheese))
combportions$Bakery=as.numeric(as.character(combportions$Bakery))

cb5=summarise(group_by(combportions,Month),bakery=sum(Bakery, na.rm=TRUE))
cb6=summarise(group_by(combportions,Month),cheese=sum(Cheese, na.rm=TRUE))
cb7=summarise(group_by(combportions,Month),jam=sum(Jam, na.rm=TRUE))
cb8=summarise(group_by(combportions,Month),maple=sum(Maple, na.rm=TRUE))

combportions2=cbind(cb5, cb6$cheese, cb7$jam, cb8$maple)
colnames(combportions2)=c("Month", "Bakery", "Cheese", "Jam", "Maple")
combportions2$Month=as.numeric(as.character(combportions2$Month))

combportions3<- melt(combportions2[,c("Month", "Bakery", "Cheese", "Jam", "Maple")],id.vars = 1)


ggplot(data = combportions3, mapping = aes(x = Month, y = value, color = variable)) +
    geom_point()+
    geom_line()+
    labs(x = "Month", y = "Percent of Markets Selling (%)", colour="Product Type")+
    theme_minimal()+
  ggtitle("Percent of Markets Selling Each Specialty Product Over the Months")+
  scale_x_continuous(breaks= seq(1, 12, by = 1), labels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"))



#compare cash method and products
```



```{r}
#popularity of health conscious over the years

comb$year=as.numeric(as.character(comb$year))
combtofu=data.frame(cbind(comb$year, fm$Organic, fm$Tofu, fm$WildHarvested))
combtofu$tally=1
colnames(combtofu)=c("year", "Organic", "Tofu", "WildHarvested", "Tally")
combtofu$year=as.numeric(as.character(combtofu$year))

t1=summarise(group_by(combtofu,year,Organic),org=sum(Tally, na.rm=TRUE))
t1=na.omit(t1)
t1$Organic=as.character(t1$Organic)
t2=dcast(t1, year ~ Organic, mean)
t2=t2[,-2]
t2$Organic_portion=1
t2$Organic_portion=round(((t2$Y/(t2$Y+t2$N))*100),digits=0)
t2$Organic_portion <- replace(t2$Organic_portion, is.nan(t2$Organic_portion), 0)


a1=summarise(group_by(combtofu,year,Tofu),org=sum(Tally, na.rm=TRUE))
a1=na.omit(a1)
a1$Tofu=as.character(a1$Tofu)
a2=dcast(a1, year ~ Tofu, mean)
a2$Tofu_portion=1
a2$Tofu_portion=round(((a2$Y/(a2$Y+a2$N))*100),digits=0)
a2$Tofu_portion <- replace(a2$Tofu_portion, is.nan(a2$Tofu_portion), 0)


l1=summarise(group_by(combtofu,year,WildHarvested),org=sum(Tally, na.rm=TRUE))
l1=na.omit(l1)
l1$WildHarvested=as.character(l1$WildHarvested)
l2=dcast(l1, year ~ WildHarvested, mean)
l2$Wild_portion=1
l2$Wild_portion=round(((l2$Y/(l2$Y+l2$N))*100),digits=0)
l2$Wild_portion <- replace(l2$Wild_portion, is.nan(l2$Wild_portion), 0)



spportions=data.frame(cbind(t2$year, t2$Organic_portion, a2$Tofu_portion, l2$Wild_portion))

colnames(spportions)=c("Year", "Organic", "Tofu", "Wild_Harvested")

spportions2<- melt(spportions[,c("Year", "Organic", "Tofu", "Wild_Harvested")],id.vars = 1)

spportions2$value=as.numeric(as.character(spportions2$value))
spportions2=spportions2[-c(1,12,13,24,25,36),]



ggplot(data = spportions2, mapping = aes(x = Year, y = value, color = variable)) +
    geom_point()+
    geom_line()+
    labs(x = "Year", y = "Percent of Markets Selling (%)", colour="Product Type")+
    theme_minimal()+
  ggtitle("Percent of Markets Selling Each Specialty Product Over the Years")+
  scale_x_continuous(breaks= seq(2010, 2019, by = 1))

```

```{r}
comb$year=as.numeric(as.character(comb$year))

combtemp=comb
```

```{r}
#popularity of health conscious over the years in areas

comb=dplyr::filter(combtemp,region== "West")

combtofu=data.frame(cbind(comb$year, fm$Organic, fm$Tofu, fm$WildHarvested))
combtofu$tally=1
colnames(combtofu)=c("year", "Organic", "Tofu", "WildHarvested", "Tally")
combtofu$year=as.numeric(as.character(combtofu$year))

t1=summarise(group_by(combtofu,year,Organic),org=sum(Tally, na.rm=TRUE))
t1=na.omit(t1)
t1$Organic=as.character(t1$Organic)
t2=dcast(t1, year ~ Organic, mean)
t2=t2[,-2]
t2$Organic_portion=1
t2$Organic_portion=round(((t2$Y/(t2$Y+t2$N))*100),digits=0)
t2$Organic_portion <- replace(t2$Organic_portion, is.nan(t2$Organic_portion), 0)


a1=summarise(group_by(combtofu,year,Tofu),org=sum(Tally, na.rm=TRUE))
a1=na.omit(a1)
a1$Tofu=as.character(a1$Tofu)
a2=dcast(a1, year ~ Tofu, mean)
a2$Tofu_portion=1
a2$Tofu_portion=round(((a2$Y/(a2$Y+a2$N))*100),digits=0)
a2$Tofu_portion <- replace(a2$Tofu_portion, is.nan(a2$Tofu_portion), 0)


l1=summarise(group_by(combtofu,year,WildHarvested),org=sum(Tally, na.rm=TRUE))
l1=na.omit(l1)
l1$WildHarvested=as.character(l1$WildHarvested)
l2=dcast(l1, year ~ WildHarvested, mean)
l2$Wild_portion=1
l2$Wild_portion=round(((l2$Y/(l2$Y+l2$N))*100),digits=0)
l2$Wild_portion <- replace(l2$Wild_portion, is.nan(l2$Wild_portion), 0)



spportions=data.frame(cbind(t2$year, t2$Organic_portion, a2$Tofu_portion, l2$Wild_portion))

colnames(spportions)=c("Year", "Organic", "Tofu", "Wild_Harvested")

spportions2<- melt(spportions[,c("Year", "Organic", "Tofu", "Wild_Harvested")],id.vars = 1)

spportions2$value=as.numeric(as.character(spportions2$value))
spportions2=spportions2[-c(1,10,19),]

library(ggplot2)

a=ggplot(data = spportions2, mapping = aes(x = Year, y = value, color = variable)) +
    geom_point()+
    geom_line()+
    labs(x = "Year", y = "Percent of Markets Selling (%)", colour="Product Type")+
    theme_minimal()+
  ggtitle("WEST REGION")+
  scale_x_continuous(breaks= seq(2010, 2019, by = 1))+theme(axis.text.x=element_text(angle = -270, hjust = 0))
  
```

```{r}
library(gridExtra)
grid.arrange(a,b,nrow = 1,top = "Percent of Markets Selling Each Product Over The Years By Region")
```

